export default {
    templateId: "Template ID",
    version: "Version",
    parentLanguageId: "Parent Language ID",
    iconName: "Icon Name",
    note: "Note",
    pushTitle1: "Push Title 1",
    pushMsg1: "Push Message 1",
    pushTitle2: "Push Title 2",
    pushMsg2: "Push Message 2",
    webInboxSubject: "Web Inbox Subject",
    webInboxMsg: "Web Inbox Message",
    webInboxDetails: "Web Inbox Details",
    webInboxIsHtml: "Web Inbox Is HTML",
    webInboxTemplateId: "Web Inbox Template ID",
    emailSubject: "Email Subject",
    emailMsg: "Email Message",
    emailMsgHtml: "Email Message (HTML)",
    emailIsHtml: "Email Is HTML",
    emailAuth: "Email Auth",
    emailImages: "Email Images",
    smsMsg: "SMS Message",
    cta_description: "CTA Description",
    ctaLink: "CTA Link",
    ctaButtonLabel: "CTA Button Label",
    pushDeepLink: "Push Deep Link",
};
